<?php

use Krystal\Form\Element;

defined('KRYSTAL') or die;

?>

<form class="card" data-group="marker" autocomplete="off">
    <?= Element::hidden('marker[id]', $marker->getId()); ?>
    <?= Element::hidden('marker[map_id]', $marker->getMapId()); ?>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Latitude'); ?></label>

        <div class="col-lg-10">
            <?= Element::text('marker[lat]', $marker->getLat(), array('class' => 'form-control')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Longitude'); ?></label>

        <div class="col-lg-10">
            <?= Element::text('marker[lng]', $marker->getLng(), array('class' => 'form-control')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Draggable'); ?></label>

        <div class="col-lg-10">
            <?= Element::checkbox('marker[draggable]', $marker->getDragable()); ?>
        </div>
    </div>

    <?php $this->loadPartial('actions', array(
        'new' => !$marker->getId(),
        'add' => 'Map:Admin:MapMarker@addAction',
        'edit' => 'Map:Admin:MapMarker@editAction',
        'save' => 'Map:Admin:MapMarker@saveAction',
        'cancel' => array('Map:Admin:Map@editAction', $marker->getMapId())
    )); ?>

</form>