<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form class="card" data-group="map" autocomplete="off">
    <?= Element::hidden('map[id]', $map->getId()); ?>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Latitude'); ?></label>
        <div class="col-lg-10">
            <?= Element::text('map[lat]', $map->getLat(), array('class' => 'form-control')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Longitude'); ?></label>
        <div class="col-lg-10">
            <?= Element::text('map[lng]', $map->getLng(), array('class' => 'form-control')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Zoom'); ?></label>
        <div class="col-lg-10">
            <?= Element::text('map[zoom]', $map->getZoom(), array('class' => 'form-control')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('API Key'); ?></label>
        <div class="col-lg-10">
            <?= Element::text('map[api_key]', $map->getApiKey(), array('class' => 'form-control')); ?>
        </div>
    </div>

    <?php $this->loadPartial('actions', array(
        'new' => !$map->getId(),
        'add' => 'Map:Admin:Map@addAction',
        'edit' => 'Map:Admin:Map@editAction',
        'save' => 'Map:Admin:Map@saveAction',
        'cancel' => 'Map:Admin:Map@indexAction'
    )); ?>

</form>

