<?php

use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;
use Krystal\Form\Element;

defined('KRYSTAL') or die;

?>

<div class="card">
    <form data-group="map" autocomplete="off">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#map"><i class="fas fa-map"></i> <?php $this->show('Map'); ?></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#map-design"><i class="fas fa-paint-brush"></i> <?php $this->show('Appearance'); ?></a>
            </li>

            <?php if ($markers !== false): ?>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#markers"><i class="fas fa-map-marker-alt"></i> <?php $this->show('Markers'); ?> <span class="text-muted">(<?= count($markers); ?>)</span></a>
            </li>
            <?php endif; ?>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="map">
                <?= $this->field()->hidden('map[id]', $map->getId()); ?>
                <?= $this->field('Map name')->text('map[name]', $map->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Map name should cover its intentions'))); ?>
                <?= $this->field('Latitude')->text('map[lat]', $map->getLat(), array('class' => 'form-control')); ?>
                <?= $this->field('Longitude')->text('map[lng]', $map->getLng(), array('class' => 'form-control')); ?>
                <?= $this->field('Language')->select('map[language]', $mapLanguages, $map->getLanguage(), array('class' => 'form-control'), null); ?>
                <?= $this->field('API Key')->text('map[api_key]', $map->getApiKey(), array('class' => 'form-control')); ?>

                <?php $this->loadPartial('actions', array(
                    'new' => !$map->getId(),
                    'add' => 'Map:Admin:Map@addAction',
                    'edit' => 'Map:Admin:Map@editAction',
                    'save' => 'Map:Admin:Map@saveAction',
                    'cancel' => 'Map:Admin:Map@indexAction'
                )); ?>

            </div>

            <div class="tab-pane" id="map-design">
                <?= $this->field('Height (px)')->number('map[height]', $map->getHeight(), array('class' => 'form-control', 'placeholder' => $this->translate('Define map height in pixels'))); ?>
                <?= $this->field('Zoom')->text('map[zoom]', $map->getZoom(), array('class' => 'form-control')); ?>
                <?= $this->field('Map type')->select('map[type]', $this->translateArray($mapTypes), $map->getType(), array('class' => 'form-control')); ?>
                <?= $this->field('Gesture handling')->select('map[gesture]', $this->translateArray($mapGestures), $map->getGesture(), array('class' => 'form-control')); ?>

                <?php if ($markers): ?>
                <div class="form-group">
                    <label class="col-lg-12"><?php $this->show('Shared icon for all markers'); ?></label>
                    <div class="col-lg-10">

                        <?php if ($map->getIcon()): ?>
                        <p><img class="img-fluid" src="<?= $map->getIcon(); ?>"></p>
                        <p><?php $this->show('Remove this icon'); ?> <?= Element::checkbox('purge', false, array(), false); ?></p>
                        <?php endif; ?>

                        <?= Element::fileData('map[icon]', $map->getIcon(), 'image/png', array('class' => 'form-control')); ?>
                    </div>
                </div>

                <?= $this->field('Clustering for all markers')->checkbox('map[clustering]', $map->getClustering()); ?>
                <?php endif; ?>

                <?= $this->field('Custom style')->textarea('map[style]', $map->getStyle(), array('rows' => 8, 'class' => 'form-control', 'placeholder' => $this->translate('Insert custom style JavaScript array'))); ?>
            </div>

            <?php if ($markers !== false): ?>
            <div class="tab-pane fade" id="markers">
                <h2 class="mt-4 mb-4 ml-0"><i class="fas fa-map-marker-alt"></i> <?php $this->show('Markers'); ?> <small>(<?= count($markers); ?>)</small></h2>

                <p>
                    <a class="btn btn-primary btn-sm" href="<?= $this->url('Map:Admin:MapMarker@addAction', $map->getId()); ?>"><i class="fas fa-map-marker-alt"></i> <?php $this->show('Add new marker'); ?></a>
                </p>

                <?= $this->widget(new GridViewWidget($markers, array(
                    'tableClass' => 'table table-hover table-bordered table-striped',
                    'columns' => array(
                        array(
                            'column' => 'id',
                            'label' => '#'
                        ),

                        array(
                            'column' => 'lat',
                            'label' => 'Latitude'
                        ),

                        array(
                            'column' => 'lng',
                            'label' => 'Longitude'
                        ),

                        array(
                            'column' => 'draggable',
                            'translateable' => true,
                            'value' => function($row){
                                return $row['draggable'] ? 'Yes' : 'No';
                            }
                        ),

                        array(
                            'column' => 'popup',
                            'label' => 'Automatically popup',
                            'translateable' => true,
                            'value' => function($row){
                                return $row['popup'] ? 'Yes' : 'No';
                            }
                        )
                    ),

                    'actions' => array(
                        'inherit' => function($row){
                            return Icon::button(
                                'fas fa-object-ungroup',
                                $this->url('Map:Admin:MapMarker@inheritAction', $row['id']),
                                $this->translate('Inherit coordinates from a parent map')
                            );
                        },

                        'edit' => function($row){
                            return Icon::edit(
                                $this->url('Map:Admin:MapMarker@editAction', $row['id']),
                                $this->translate('Edit this marker')
                            );
                        },

                        'remove' => function($row){
                            return Icon::remove(
                                $this->url('Map:Admin:MapMarker@deleteAction', $row['id']), 
                                $this->translate('Remove this marker')
                            );
                        }
                    )
                ))); ?>
            </div>
            <?php endif; ?>
        </div>
    </form>
</div>