<?php

use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;
use Krystal\Form\Element;

?>

<div class="card">
    <form autocomplete="off">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-bs-toggle="tab" href="#map"><i class="fas fa-map"></i> <?= $this->translate('Map'); ?></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#map-design"><i class="fas fa-paint-brush"></i> <?= $this->translate('Appearance'); ?></a>
            </li>

            <?php if ($markers !== false): ?>
            <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#markers"><i class="fas fa-map-marker-alt"></i> <?= $this->translate('Markers'); ?> <span class="text-muted">(<?= count($markers); ?>)</span></a>
            </li>
            <?php endif; ?>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content pt-3">
            <div class="tab-pane show active" id="map">
                <?= Element::hidden('map[id]', $map->getId()); ?>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('Map name'); ?></label>
                    <div class="col-lg-10">
                        <?= Element::text('map[name]', $map->getName(), ['class' => 'form-control', 'placeholder' => $this->translate('Map name should cover its intentions')]); ?>
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('Latitude'); ?></label>
                    <div class="col-lg-10">
                        <?= Element::text('map[lat]', $map->getLat(), ['class' => 'form-control']); ?>
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('Longitude'); ?></label>
                    <div class="col-lg-10">
                        <?= Element::text('map[lng]', $map->getLng(), ['class' => 'form-control']); ?>
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('Language'); ?></label>
                    <div class="col-lg-10">
                        <?= Element::select('map[language]', $mapLanguages, $map->getLanguage(), ['class' => 'form-select'], ''); ?>
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('API Key'); ?></label>
                    <div class="col-lg-10">
                        <?= Element::text('map[api_key]', $map->getApiKey(), ['class' => 'form-control']); ?>
                    </div>
                </div>

                <?php $this->loadPartial('actions', [
                    'new' => !$map->getId(),
                    'add' => 'Map:Admin:Map@addAction',
                    'edit' => 'Map:Admin:Map@editAction',
                    'save' => 'Map:Admin:Map@saveAction',
                    'cancel' => 'Map:Admin:Map@indexAction'
                ]); ?>

            </div>

            <div class="tab-pane" id="map-design">
                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('Height (px)'); ?></label>
                    <div class="col-lg-10">
                        <?= Element::number('map[height]', $map->getHeight(), ['class' => 'form-control', 'placeholder' => $this->translate('Define map height in pixels')]); ?>
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('Zoom'); ?></label>
                    <div class="col-lg-10">
                        <?= Element::text('map[zoom]', $map->getZoom(), ['class' => 'form-control']); ?>
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('Map type'); ?></label>
                    <div class="col-lg-10">
                        <?= Element::select('map[type]', $this->translateArray($mapTypes), $map->getType(), ['class' => 'form-select']); ?>
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('Gesture handling'); ?></label>
                    <div class="col-lg-10">
                        <?= Element::select('map[gesture]', $this->translateArray($mapGestures), $map->getGesture(), ['class' => 'form-select']); ?>
                    </div>
                </div>

                <?php if ($markers): ?>
                <div class="mb-3">
                    <label class="col-lg-12"><?= $this->translate('Shared icon for all markers'); ?></label>
                    <div class="col-lg-10">

                        <?php if ($map->getIcon()): ?>
                        <p><img class="img-fluid" src="<?= $map->getIcon(); ?>"></p>
                        <p><?= $this->translate('Remove this icon'); ?> <?= Element::checkbox('purge', false, [], false); ?></p>
                        <?php endif; ?>

                        <?= Element::fileData('map[icon]', $map->getIcon(), 'image/png', ['class' => 'form-control']); ?>
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('Routed'); ?></label>
                    <div class="col-lg-10">
                        <div class="form-check">
                            <?= Element::checkbox('map[routed]', $map->getRouted(), ['class' => 'form-check-input']); ?>
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('Clustering for all markers'); ?></label>
                    <div class="col-lg-10">
                        <div class="form-check">
                            <?= Element::checkbox('map[clustering]', $map->getClustering(), ['class' => 'form-check-input']); ?>
                        </div>
                    </div>
                </div>
                <?php endif; ?>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('Static'); ?></label>
                    <div class="col-lg-10">
                        <div class="form-check">
                            <?= Element::checkbox('map[static]', $map->getStatic(), ['class' => 'form-check-input']); ?>
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('Custom style'); ?></label>
                    <div class="col-lg-10">
                        <?= Element::textarea('map[style]', $map->getStyle(), ['rows' => 8, 'class' => 'form-control', 'placeholder' => $this->translate('Insert custom style JavaScript array')]); ?>
                    </div>
                </div>
            </div>

            <?php if ($markers !== false): ?>
            <div class="tab-pane fade" id="markers">
                <!-- Header -->
                <div class="row pt-2">
                    <div class="col-6">
                        <h3 class="ms-0"><i class="fas fa-map-marker-alt"></i> <?= $this->translate('Markers'); ?> <small class="text-muted">(<?= count($markers); ?>)</small></h3>
                    </div>
                    
                    <div class="col-6 text-lg-end">
                        <a class="btn btn-primary btn-sm" href="<?= $this->url('Map:Admin:MapMarker@addAction', $map->getId()); ?>"><i class="fas fa-map-marker-alt"></i> <?= $this->translate('Add new marker'); ?></a>
                    </div>
                </div>

                <?= $this->widget(new GridViewWidget($markers, [
                    'tableClass' => 'table table-hover table-bordered table-striped',
                    'columns' => [
                        [
                            'column' => 'id',
                            'label' => '#'
                        ],

                        [
                            'column' => 'address',
                        ],
                        
                        [
                            'column' => 'lat',
                            'label' => 'Latitude'
                        ],

                        [
                            'column' => 'lng',
                            'label' => 'Longitude'
                        ],

                        [
                            'column' => 'order'
                        ],

                        [
                            'column' => 'popup',
                            'label' => 'Automatically popup',
                            'translateable' => true,
                            'value' => function($row){
                                return $row['popup'] ? 'Yes' : 'No';
                            }
                        ]
                    ],

                    'actions' => [
                        function($row){
                            return Icon::button(
                                'fas fa-object-ungroup',
                                $this->url('Map:Admin:MapMarker@inheritAction', $row['id']),
                                $this->translate('Inherit coordinates from a parent map')
                            );
                        },

                        function($row){
                            return Icon::edit(
                                $this->url('Map:Admin:MapMarker@editAction', $row['id']),
                                $this->translate('Edit this marker')
                            );
                        },

                        function($row){
                            return Icon::remove(
                                $this->url('Map:Admin:MapMarker@deleteAction', $row['id']), 
                                $this->translate('Remove this marker')
                            );
                        }
                    ]
                ])); ?>
            </div>
            <?php endif; ?>
        </div>
    </form>
</div>