<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

?>

<div class="btn-toolbar">
    <div class="btn-group me-2">
        <a class="btn btn-primary" href="<?= $this->url('Map:Admin:Map@addAction'); ?>"><?= $this->translate('Add new map'); ?></a>
    </div>
</div>

<div class="card card-body">
    <h4><i class="fas fa-map"></i> <?= $this->translate('Maps'); ?> <small>(<?= count($maps); ?>)</small></h4>
    <hr >

    <?= $this->widget(new GridViewWidget($maps, [
        'tableClass' => 'table table-hover table-bordered table-striped',
        'columns' => [
            [
                'column' => 'id',
                'label' => '#'
            ],

            [
                'column' => 'name'
            ],

            [
                'column' => 'lat',
                'label' => 'Latitude'
            ],

            [
                'column' => 'lng',
                'label' => 'Longitude'
            ],

            [
                'column' => 'zoom'
            ],

            [
                'column' => 'marker_count'
            ]
        ],

        'actions' => [
            function($row){
                return Icon::view(
                    $this->url('Map:Admin:Map@viewAction', $row['id']),
                    $this->translate('View this map'),
                    false
                );
            },

            function($row){
                return Icon::edit(
                    $this->url('Map:Admin:Map@editAction', $row['id']),
                    $this->translate('Edit this map')
                );
            },

            function($row){
                return Icon::remove(
                    $this->url('Map:Admin:Map@deleteAction', $row['id']), 
                    $this->translate('Remove this map')
                );
            }
        ]
    ])); ?>

    <?php if (empty($maps)): ?>
    <div class="center-block">
        <h2 class="text-center text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No maps'); ?></h2>
    </div>
    <?php endif; ?>
</div>