<?php

use Krystal\Security\Filter;
use Map\Service\MapService;

// Append required scripts to run maps
$this->getPluginBag()->appendScripts(array(
    MapService::createServiceUrl($config['key'], $config['language']),
    '@Map/google.maps.js'
));

?>

<div id="<?= $config['id']; ?>" style="height: <?= $config['height']; ?>px;"></div>
<input type="hidden" class="map-configuration-input" value="<?= Filter::specialChars(json_encode($config)); ?>" />
