<?php

use Krystal\Security\Filter;
use Map\Service\MapService;

// Do this map require clustering library?
if ($config['clustering'] == true) {
    $this->getPluginBag()->appendScript('https://unpkg.com/@google/markerclustererplus@4.0.1/dist/markerclustererplus.min.js');
}

// Append required scripts to run maps
$this->getPluginBag()->appendScripts(array(
    MapService::createServiceUrl($config['key'], $config['language']),
    '@Map/google.maps.js?'.time()
));

?>

<div id="<?= $config['id']; ?>" style="height: <?= $config['height']; ?>px;"></div>
<input type="hidden" class="map-configuration-input" value="<?= Filter::specialChars(json_encode($config)); ?>" />
